const USER_ACTION_TYPES = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SIGN_OUT_CURRENT_USER: 'SIGN_OUT_CURRENT_USER',
  SIGN_UP_START: 'SIGN_UP_START',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
  SIGN_IN_CURRENT_USER: 'SIGN_IN_CURRENT_USER',
  SIGN_IN_GOOGLE_CURRENT_USER: 'SIGN_IN_GOOGLE_CURRENT_USER',
}

export default USER_ACTION_TYPES
